//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ris2022.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ris2022.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance Type.
        /// </summary>
        public static string Acceptancetype {
            get {
                return ResourceManager.GetString("Acceptancetype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Patient.
        /// </summary>
        public static string AddPatient {
            get {
                return ResourceManager.GetString("AddPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adminstration.
        /// </summary>
        public static string Adminstration {
            get {
                return ResourceManager.GetString("Adminstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string AlignDir {
            get {
                return ResourceManager.GetString("AlignDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string CallUs {
            get {
                return ResourceManager.GetString("CallUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinic.
        /// </summary>
        public static string Clinic {
            get {
                return ResourceManager.GetString("Clinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor Name.
        /// </summary>
        public static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string FathName {
            get {
                return ResourceManager.GetString("FathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martial Status.
        /// </summary>
        public static string Martialstatus {
            get {
                return ResourceManager.GetString("Martialstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality.
        /// </summary>
        public static string Modality {
            get {
                return ResourceManager.GetString("Modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality Type.
        /// </summary>
        public static string Modalitytype {
            get {
                return ResourceManager.GetString("Modalitytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiographs Orders.
        /// </summary>
        public static string OrderIndex {
            get {
                return ResourceManager.GetString("OrderIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string Ordertype {
            get {
                return ResourceManager.GetString("Ordertype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Id.
        /// </summary>
        public static string PatId {
            get {
                return ResourceManager.GetString("PatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string Patients {
            get {
                return ResourceManager.GetString("Patients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Type.
        /// </summary>
        public static string Paytype {
            get {
                return ResourceManager.GetString("Paytype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Type.
        /// </summary>
        public static string Proceduretype {
            get {
                return ResourceManager.GetString("Proceduretype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radiology Information System.
        /// </summary>
        public static string RIS {
            get {
                return ResourceManager.GetString("RIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string SurName {
            get {
                return ResourceManager.GetString("SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type.
        /// </summary>
        public static string Worktype {
            get {
                return ResourceManager.GetString("Worktype", resourceCulture);
            }
        }
    }
}
