// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Ris2022.Data;

#nullable disable

namespace Ris2022.Data.Migrations
{
    [DbContext(typeof(RisDBContext))]
    [Migration("20220822201245_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 30);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ris2022.Data.Models.Acceptancetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Acceptancetypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Cost")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Namear")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Martialstatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Martialstatuses");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Aetitle")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Departmentid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Ipaddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Modalitytypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Port")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Modalities");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Modalitytype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Modalitytypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Accessionnumber")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Autoexpiredate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Clinicid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Deptid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Doctorid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Documentid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Enddate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("Insertdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Insertuserid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Modalityid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Modalitytypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Ordertypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Patientid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Payreasonid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Paytypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Proceduretypeid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Reasonid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Startdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Statusid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Studyid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Updatedate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("Updateuserid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Deptid");

                    b.HasIndex("Modalityid");

                    b.HasIndex("Modalitytypeid");

                    b.HasIndex("Ordertypeid");

                    b.HasIndex("Patientid");

                    b.HasIndex("Paytypeid");

                    b.HasIndex("Proceduretypeid");

                    b.HasIndex("Reasonid");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Ordertype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Ordetypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<int?>("Gendre")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Givenid")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.Property<string>("Middlename")
                        .HasMaxLength(25)
                        .HasColumnType("NVARCHAR2(25)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Paytype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Paytypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Proceduretype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Parentnum")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Proceduretypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Reason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Reasons");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<byte[]>("Alergy")
                        .HasColumnType("RAW(2000)");

                    b.Property<int?>("Approved")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool?>("Approveddoctorid")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Audiopath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Imagedate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("Meidcalhistory")
                        .HasColumnType("RAW(2000)");

                    b.Property<byte[]>("Notes")
                        .HasColumnType("RAW(2000)");

                    b.Property<int>("Orderid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Parentreport")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Patientid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Physicianid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Raddoctorid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("Referingdoctorid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<byte[]>("Reportbody")
                        .HasColumnType("RAW(2000)");

                    b.Property<DateTime>("Reportdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Seriesnumber")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<byte[]>("Title")
                        .HasColumnType("RAW(2000)");

                    b.HasKey("Id");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Risuser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Departmentid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Firstname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool?>("Isdoctor")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("Languageid")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Lastname")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Userroleid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("Risusers");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Userrole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Userroles");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Worktype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Namear")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nameen")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Worktypes");
                });

            modelBuilder.Entity("Ris2022.Data.Models.Order", b =>
                {
                    b.HasOne("Ris2022.Data.Models.Department", "dept")
                        .WithMany()
                        .HasForeignKey("Deptid");

                    b.HasOne("Ris2022.Data.Models.Modality", "modality")
                        .WithMany()
                        .HasForeignKey("Modalityid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.Modalitytype", "modalitytype")
                        .WithMany()
                        .HasForeignKey("Modalitytypeid");

                    b.HasOne("Ris2022.Data.Models.Ordertype", "Ordertype")
                        .WithMany()
                        .HasForeignKey("Ordertypeid");

                    b.HasOne("Ris2022.Data.Models.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("Patientid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ris2022.Data.Models.Paytype", "paytype")
                        .WithMany()
                        .HasForeignKey("Paytypeid");

                    b.HasOne("Ris2022.Data.Models.Proceduretype", "proceduretype")
                        .WithMany()
                        .HasForeignKey("Proceduretypeid");

                    b.HasOne("Ris2022.Data.Models.Reason", "reason")
                        .WithMany()
                        .HasForeignKey("Reasonid");

                    b.Navigation("Ordertype");

                    b.Navigation("dept");

                    b.Navigation("modality");

                    b.Navigation("modalitytype");

                    b.Navigation("patient");

                    b.Navigation("paytype");

                    b.Navigation("proceduretype");

                    b.Navigation("reason");
                });
#pragma warning restore 612, 618
        }
    }
}
